Add tests/docs for help

diff --git a/examples/lib/appspec b/examples/lib/appspec
--- a/examples/lib/appspec
+++ b/examples/lib/appspec
@@ -18,7 +18,8 @@ APPSPEC.run() {
 
 APPSPEC.run-op() {
   if (( ${#ERRORS[*]} > 0 )); then
-    debug "ERRORS: (${ERRORS[*]})"
+    echo "ERRORS: (${ERRORS[*]})" >&2
+    exit 1
   else
     debug "OP: $OP"
   fi
@@ -478,7 +479,7 @@ APPSPEC.parse-test1() {
 
 APPSPEC.cmd_help() {
   echo help
-  source "$APPSPECDIR/help/help.bash"
+  source "$APPSPECDIR/lib/help"
   COMMANDS=("${COMMANDS[@]:1}")
   if [[ -n "$COMMANDS" ]]; then
     local func="${COMMANDS[*]}"
