Add ansi color support

diff --git a/examples/lib/appspec b/examples/lib/appspec
--- a/examples/lib/appspec
+++ b/examples/lib/appspec
@@ -1,25 +1,38 @@
 #!/bin/bash
 
 # Generated by perl modules
-# App::Spec v0.011
+# App::Spec v0.012
 # App::Spec::Bash v0.000
 # mydemo - Demo
 
 declare OP=
 declare -a ERRORS=()
 declare -a COMMANDS=()
+declare stdout_terminal=false stderr_terminal=false
+declare APPSPEC_COLOR_BOLD='\x1b[1m'
+declare APPSPEC_COLOR_RED='\x1b[31m'
+declare APPSPEC_COLOR_ERROR="$GIT_HUB_COLOR_RED$GIT_HUB_COLOR_BOLD"
+declare APPSPEC_COLOR_GREEN='\x1b[32m'
+declare APPSPEC_COLOR_CYAN='\x1b[36m'
+declare APPSPEC_COLOR_MAGENTA='\x1b[35m'
+declare APPSPEC_COLOR_YELLOW='\x1b[33m'
+declare APPSPEC_COLOR_DARKGRAY='\x1b[90m'
+declare APPSPEC_NO_COLOR='\x1b[0m'
+
+
 
 DEBUG=false
 [[ -n "$APPSPEC_BASH_DEBUG" ]] && DEBUG=true
 
 APPSPEC.run() {
+  APPSPEC.init-terminal
   APPSPEC.parse $@
 }
 
 APPSPEC.run-op() {
   if (( ${#ERRORS[*]} > 0 )); then
     APPSPEC.cmd_help
-    echo "ERRORS: (${ERRORS[*]})" >&2
+    APPSPEC.error "${ERRORS[*]}"
     exit 1
   else
     debug "OP: $OP"
@@ -490,8 +503,70 @@ APPSPEC.parse-test1() {
 
 
 
+
+APPSPEC.colored() {
+    local fh="$1"
+    local message="$2"
+    if [[ "$fh" == "stdout" ]] && ! $stdout_terminal; then
+        echo "$message"
+        return
+    fi
+    if [[ "$fh" == stderr ]] && ! $stderr_terminal; then
+        echo "$message"
+        return
+    fi
+    shift
+    shift
+    local colornames=($@)
+    local varname value colored=
+
+    for i in ${colornames[@]}; do
+        varname="APPSPEC_COLOR_$i"
+        value="${!varname}"
+        colored+="$value"
+    done
+
+    colored+="$message"
+    colored+="$APPSPEC_NO_COLOR"
+    echo "$colored"
+
+}
+
+APPSPEC.colorize() {
+    local fh="$1"
+    local message="$2"
+    shift
+    shift
+    [[ "$fh" == stdout ]] && echo -e "$(APPSPEC.colored "$fh" "$message" $@)"
+    [[ "$fh" == stderr ]] && echo -e "$(APPSPEC.colored "$fh" "$message" $@)" >&2
+}
+
+APPSPEC.say() {
+    local message="$1"
+    shift
+    if [[ $# -gt 0 ]]; then
+        echo -e "$(APPSPEC.colored stdout "$message" $@)"
+    else
+        echo "$message"
+    fi
+}
+
+APPSPEC.error() {
+    local message="$1"
+    echo -e "$(APPSPEC.colored stderr "$message" BOLD RED)" >&2
+}
+
+APPSPEC.init-terminal() {
+  if [[ -t 1 ]]; then
+    stdout_terminal=true
+  fi
+  if [[ -t 2 ]]; then
+    stderr_terminal=true
+  fi
+}
+
+
 APPSPEC.cmd_help() {
-  echo help
   source "$APPSPECDIR/lib/help"
   COMMANDS=("${COMMANDS[@]:1}")
   if [[ -n "$COMMANDS" ]]; then
@@ -509,5 +584,5 @@ shift_arg() {
 }
 
 debug() {
-  $DEBUG && echo $@
+  $DEBUG && APPSPEC.colorize stderr "$@" DARKGRAY
 }
